global:
  experiment_name: 'spectrogram_cnn_ranknet'
  seed: 42
  debug: false
  device: 'auto'
  output_dir: 'results'

data:
  type: 'spectrogram'
  source:
    wav_dir: 'tests/dataloader_test/dataset_test'
    spectrogram_dir: 'tests/dataloader_test/generated_spectrograms'
  preprocessing:
    spectrogram:
      method: 'mel'
      n_mels: 128
      n_fft: 1024
      hop_length: 512
      power: 2.0
      normalized: true
      save_dir: 'tests/dataloader_test/generated_spectrograms'
  splits:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    split_by_patient: true
    split_seed: 42
  dataloader:
    batch_size: 16
    num_workers: 2
    pin_memory: true
    drop_last: false

model:
  type: 'cnn'
  parameters:
    input_channels: 3
    input_size: [224, 224]
    filters: [32, 64, 128]
    kernel_sizes: [3, 3, 3]
    pool_sizes: [2, 2, 2]
    fc_dims: [256, 128]
    num_classes: 1
    dropout_rate: 0.3
    batch_norm: true
    activation: 'relu'
    is_classification: false

training:
  epochs: 50
  save_every: 10
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  loss:
    type: 'RankNetLoss'
    parameters:
      sigma: 1.0
      sampling_ratio: 0.5
  optimizer:
    type: 'Adam'
    parameters:
      lr: 0.001
      weight_decay: 0.0001
  scheduler:
    type: 'CosineAnnealingLR'
    parameters:
      T_max: 50
      eta_min: 0.00001

evaluation:
  metrics: ['mse', 'mae', 'ndcg']
  ndcg_k: 5
  log_predictions: true
  confusion_matrix: false 